export const people = ['Ignacio Valeria', 'Benjamín Flores', 'Benjamín Palma'] as const;
export type Person = typeof people[number];
export type Slide = { id: number; title: string; short: string; category: string; seconds: number; message: string; prompt: string; points: [string,string][]; visual: string; foundation: string; source: string; avoid: string };
export const slides: Slide[] = [
 {id:1,title:'Un proyecto con propósito',short:'Portada',category:'El punto de partida',seconds:15,message:'Reutilizar activos existentes antes de realizar nuevas compras.',prompt:'Presenta el proyecto en una idea: ¿qué propone y para quién?',points:[['Qué es','Segunda Vida es un marketplace web interno de mobiliario y equipamiento usado entre sucursales de Tiendas Andina.'],['Para qué','Conectar activos disponibles con sucursales que los necesitan, evitando compras innecesarias.'],['Estado','La imagen de la presentación es un mockup conceptual de la solución propuesta.']],visual:'Señala el nombre del proyecto y la imagen conceptual.',foundation:'La propuesta responde a la necesidad de aprovechar activos que ya pertenecen a la compañía.',source:'Presentación final, slide 1 · Caso oficial, Solución.',avoid:'Presentar el mockup como una plataforma ya implementada.'},
 {id:2,title:'Entender la necesidad',short:'Contexto',category:'Problema de negocio',seconds:40,message:'La falta de visibilidad impide aprovechar los activos disponibles.',prompt:'Conecta la situación actual con su impacto y la necesidad del negocio.',points:[['Situación','Más de 80 sucursales en Chile: algunas tienen activos en desuso, mientras otras necesitan artículos similares.'],['Impacto','Compras innecesarias, almacenamiento y desecho de bienes, y traslados por correo o llamadas sin trazabilidad.'],['Necesidad','Centralizar la disponibilidad y reutilización para mejorar la gestión de activos y apoyar la economía circular.']],visual:'Recorre situación actual → impacto → necesidad.',foundation:'Un catálogo común permite conocer alternativas de reutilización antes de comprar activos nuevos.',source:'Presentación, slide 2 · Caso oficial, Contexto y Problemáticas.',avoid:'Afirmar un número exacto de sucursales o un ahorro ya logrado.'},
 {id:3,title:'Del activo a su segunda vida',short:'Solución y alcance',category:'Qué vamos a desarrollar',seconds:55,message:'Cinco módulos conectan la disponibilidad de una sucursal con la necesidad de otra.',prompt:'Sigue el recorrido de un activo y recuerda qué queda fuera del alcance.',points:[['Recorrido','Publicación → Búsqueda → Solicitudes/Aprobaciones → Logística → Analítica/Reportes. Operaciones aprueba antes de autorizar el traslado.'],['Complementos','Integración funcional, pruebas con usuarios, documentación, capacitación, regla de valorización contable y puesta en marcha.'],['Límites','Venta a terceros, flota propia y reparación física quedan fuera. El alcance se deriva de necesidad → requerimientos → entregables → EDT.']],visual:'Usa el flujo entre sucursales y la franja de incluidos y excluidos.',foundation:'La EDT, o Estructura de Desglose del Trabajo, organiza los entregables en elementos más pequeños para planificarlos.',source:'Presentación, slide 3 · Caso, Funcionalidades · Plan, Gestión del Alcance.',avoid:'Confundir coordinación del traslado con disponer de transporte propio.'},
 {id:4,title:'Las personas detrás del plan',short:'Recursos',category:'Responsabilidades y disponibilidad',seconds:50,message:'Los recursos se determinan a partir del trabajo y de su disponibilidad.',prompt:'Explica cómo pasan de los entregables a las responsabilidades y dedicaciones.',points:[['Seis áreas y roles','Dirección coordina; Operaciones patrocina y aprueba; TI participa técnicamente; Sucursales valida; Logística coordina; Contabilidad valida el valor.'],['Organización','Los entregables de la EDT orientan actividades; la matriz RACI-VS establece responsabilidades y las asignaciones se coordinan con fechas y costos.'],['Restricciones','La dedicación del equipo de TI es parcial y el presupuesto máximo es CLP $115 millones.']],visual:'Conecta las áreas con la columna de organización de recursos.',foundation:'La disponibilidad de las personas condiciona el cronograma; las responsabilidades permiten coordinar a las áreas.',source:'Presentación, slide 4 · Plan, Recursos y Cronograma.',avoid:'Tratar los $115 millones como costo estimado o suponer dedicación completa de TI.'},
 {id:5,title:'Un calendario con fundamento',short:'Cronograma',category:'Secuencia y control',seconds:60,message:'La secuencia depende del trabajo, los recursos y los puntos de aprobación.',prompt:'Justifica el cronograma y recorre los seis hitos, sin limitarte a decir las fechas.',points:[['Período','Del 04/01/2027 al 30/06/2027. Máximo seis meses; lunes a viernes, ocho horas diarias y feriados nacionales considerados.'],['Criterios','Actividades de la EDT, dependencias, disponibilidad parcial de TI, seguimiento semanal y ruta crítica en Microsoft Project.'],['Hitos','H1 Acta · H2 diseño y valorización · H3 cinco módulos construidos · H4 versión integrada aprobada · H5 pruebas y decisión de puesta en marcha · H6 aceptación y puesta en marcha.']],visual:'Prioriza los criterios y la línea H1–H6. Las cinco fases dan la vista general.',foundation:'La ruta crítica es la secuencia que determina el término del proyecto; su retraso puede mover la fecha de cierre.',source:'Presentación, slide 5 · Plan, Gestión y Línea Base del Cronograma.',avoid:'Confundir jornada de ocho horas con dedicación de ocho horas de cada recurso.'},
 {id:6,title:'Planificar también es coordinar',short:'Estrategias',category:'Decisiones y beneficios',seconds:60,message:'Cada estrategia aporta un beneficio concreto de gestión.',prompt:'Relaciona las estrategias con sus beneficios y explica el enfoque del proyecto.',points:[['Enfoque','Principalmente predictivo: alcance, fechas y costos planificados, complementados con revisiones iterativas con usuarios.'],['Coordinación','Planificación integrada → control conjunto; RACI-VS → responsabilidades claras; hitos → detección temprana de desviaciones.'],['Validación','Cambios formales → evaluación de impacto antes de incorporar modificaciones; pruebas con usuarios → mejor adecuación a la necesidad.']],visual:'Relaciona cada estrategia de la izquierda con su beneficio a la derecha.',foundation:'El Director evalúa impactos de cambios en alcance, recursos, costos y fechas; Operaciones autoriza cuando modifican condiciones aprobadas.',source:'Presentación, slide 6 · Plan, Ciclo de Vida y Gestión de Cambios.',avoid:'Describir el enfoque como ágil puro o considerar informales los cambios.'},
 {id:7,title:'Un plan para esta organización',short:'Integración',category:'Contexto aplicado',seconds:50,message:'Las condiciones de Tiendas Andina se convierten en decisiones del plan.',prompt:'Une cada condición organizacional con la decisión que motivó.',points:[['Organización','Sucursales distribuidas → plataforma web centralizada; aprobación de Operaciones → flujo formal de autorización.'],['Disponibilidad y especialidad','TI compartida → dedicación parcial; Logística → coordinación de traslados; Contabilidad → criterio de valorización validado antes de construir.'],['Adopción','Pruebas con representantes de sucursales y capacitación antes de la puesta en marcha.']],visual:'Lee la relación entre las dos columnas, no una lista aislada.',foundation:'La integración considera condiciones reales de operación, coordinación y disponibilidad, además del software.',source:'Presentación, slide 7 · Plan, Interesados, Calidad y Cronograma.',avoid:'Repetir toda la slide 2: aquí importa qué decisión se tomó frente a cada condición.'},
 {id:8,title:'Elegir la herramienta por su uso',short:'Herramientas',category:'La evidencia de planificación',seconds:50,message:'Cada herramienta responde a una necesidad distinta del proyecto.',prompt:'Para cada herramienta, relaciona el documento producido con la razón de selección.',points:[['Microsoft Word','Acta, Plan de Dirección y Alcance: documentación formal respetando la estructura de las plantillas.'],['Microsoft Excel','Requerimientos, RACI-VS y Presupuesto: organización de matrices, trazabilidad y cálculos actualizables.'],['Microsoft Project','Carta Gantt: dependencias, recursos, hitos y ruta crítica. PMBOK y el material del curso son el marco de referencia.']],visual:'Herramienta → documento → razón de selección.',foundation:'Se eligen según la necesidad de documentar, organizar, calcular o planificar; el uso se evidencia en los documentos del equipo.',source:'Presentación, slide 8 · Plan, Gestión del Cronograma.',avoid:'Llamar software al PMBOK o afirmar que Project garantiza cumplir el plazo.'},
 {id:9,title:'Cerrar con la idea que importa',short:'Cierre',category:'El valor final',seconds:10,message:'Reutilizar activos existentes antes de realizar nuevas compras.',prompt:'Cierra en una idea, conecta con el propósito y termina.',points:[['Recuperar el propósito','Segunda Vida busca aprovechar mejor los activos que la compañía ya tiene.'],['Cerrar','Reafirma el mensaje de la lámina y agradece la atención.']],visual:'Apóyate en la frase central de la última slide.',foundation:'El valor esperado se vincula con compras evitadas, reutilización y reducción de residuos.',source:'Presentación, slide 9 · Caso, Modelo de Negocio.',avoid:'Abrir temas nuevos o repetir los cinco módulos en el cierre.'},
];
export const modules = [
 {title:'Publicación',action:'Hacer visible',text:'Registrar fotografías, estado de conservación, sucursal de origen y valor de referencia contable.',role:'Sucursales publican los activos disponibles.'},
 {title:'Búsqueda',action:'Encontrar',text:'Filtrar por región, tipo de activo y estado de conservación. Recibir alertas de activos buscados.',role:'Sucursales identifican alternativas a una compra nueva.'},
 {title:'Solicitudes',action:'Autorizar',text:'Solicitar formalmente el activo y obtener aprobación antes de autorizar su traslado.',role:'Operaciones aprueba los traslados.'},
 {title:'Logística',action:'Coordinar',text:'Registrar el traslado, el transportista asignado y la fecha estimada de llegada.',role:'Logística coordina el movimiento físico.'},
 {title:'Reportes',action:'Medir',text:'Informar ahorro estimado en compras evitadas y volumen de activos reutilizados.',role:'Operaciones recibe información para evaluar los beneficios.'},
];
